repos:
  - repo: https://github.com/pycqa/pylint
    rev: v3.3.8
    hooks:
      - id: pylint
        # args: [--fail-on=F,E]
        args: [
            "--disable=C0114,C0411,C0115,C0116,C0412,E0401,W0718,R1702,R0911,R0912,R0915,R1705,W0404,W0603,W0613,W0511,R0902,R1732",
          ] # example: disable missing-docstring
        additional_dependencies:
          [flask, flask-sqlalchemy, flask_jwt_extended, werkzeug]
        entry: pylint
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile=black", "--filter-files"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
        args: []
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.17.1
  #   hooks:
  #     - id: mypy
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.0 # Let autoupdate find the latest
    hooks:
      - id: clang-format
        files: \.(c|h)$
        args: [--style=file] # Assumes a .clang-format file is present
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0 # Use this specific modern version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ["--maxkb=500"]
      # The following hooks are very stable and widely available
      - id: check-ast # Check that files contain valid syntax (for any language)
      - id: check-case-conflict # Check for files that would conflict in case-insensitive filesystems
      - id: check-json # Check JSON files for validity
      - id: check-yaml # Check YAML files for validity
      - id: destroyed-symlinks # Check for destroyed symlinks
      - id: detect-private-key # Detect the presence of private keys
